"""Offline mock backend. Returns responses in the documented FortyGuard shapes,
generated by a deterministic heat model. Every response is tagged
`"source": "mock"` so mock output can never be mistaken for a real reading.

The mock resolves synchronously: a submission returns its final result directly
(with a synthetic activity_id and status "completed"). The live backend does the
real submit-then-poll dance; the planner code above it is identical either way.
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any

from . import heatmodel as hm
from .base import (
    ANALYTIC_PERSISTENCE,
    ANALYTIC_TCM,
    ANALYTIC_TIME_OF_MEASURE,
    FILTER_RANGE_OF_HOURS,
    FortyGuardClient,
    FortyGuardError,
    validate_window,
)

_CITY_COORDS = {
    "abu_dhabi": (24.45, 54.38),
    "dubai": (25.20, 55.27),
    "delhi": (28.61, 77.21),
    "phoenix": (33.45, -112.07),
}
_MOCK = {"source": "mock", "notice": "synthetic data from a deterministic model, not a real reading"}


def _climate(lat: float, lon: float) -> tuple[float, float, float]:
    best, best_d = "default", 9e9
    for name, (clat, clon) in _CITY_COORDS.items():
        d = abs(lat - clat) + abs(lon - clon)
        if d < best_d and d < 2.0:
            best, best_d = name, d
    return hm.CITY_CLIMATE[best]


def _hours(date_time: dict[str, Any]) -> tuple[str, list[float], list[str]]:
    start_date = date_time.get("start_date")
    if not start_date:
        raise FortyGuardError(400, "date_time.start_date is required.")
    start_time = date_time.get("start_time", "12:00")
    validate_window(start_date, start_time)
    filter_type = int(date_time.get("filter_type", 1))
    sh = int(start_time.split(":")[0])
    if filter_type == FILTER_RANGE_OF_HOURS:
        eh = int(date_time.get("end_time", start_time).split(":")[0])
        hours = list(range(sh, max(sh + 1, eh + 1)))
    else:
        hours = [sh]
    stamps = [f"{start_date}T{h:02d}:00:00Z" for h in hours]
    return start_date, [float(h) for h in hours], stamps


class MockFortyGuardClient:
    backend = "mock"

    def env_params(self, latitude, longitude, temperature, date_time, parameters=None):
        _, hours, stamps = _hours(date_time)
        lo, hi, td = _climate(latitude, longitude)
        shade = hm.shade_fraction(latitude, longitude)
        temps = [hm.air_temperature(lo, hi, h, latitude, longitude) for h in hours]
        rhs = [hm.rh_from_dewpoint(t, td) for t in temps]
        params = {
            "air_temperature_celsius": temps,
            "heat_index_celsius": [hm.heat_index_c(t, rh) for t, rh in zip(temps, rhs)],
            "apparent_temperature_celsius": [
                hm.apparent_temperature_c(t, rh, shade, h) for t, rh, h in zip(temps, rhs, hours)
            ],
            "wet_bulb_temperature_celsius": [hm.wet_bulb_c(t, rh) for t, rh in zip(temps, rhs)],
            "relative_humidity_percent": rhs,
            "cloud_cover_octas": [round(hm._hash_unit("cloud", latitude, longitude, h) * 8, 1) for h in hours],
        }
        if parameters:
            params = {k: v for k, v in params.items() if k in set(parameters)}
        return {
            **_MOCK,
            "metadata": {"timezone": "UTC", "timestamps": stamps},
            "locations": [
                {
                    "latitude": latitude,
                    "longitude": longitude,
                    "elevation": round(hm._hash_unit("elev", latitude, longitude) * 200, 1),
                    "parameters": params,
                    "solar_irradiance": {
                        "clear_sky": {"ghi": 900.0, "dni": 750.0, "dhi": 150.0},
                        "description": "clear-sky global/direct/diffuse irradiance, W/m^2",
                    },
                }
            ],
        }

    def heat_intelligence(self, latitude, longitude, temperature, date, analysis=None):
        validate_window(date)
        lo, hi, td = _climate(latitude, longitude)
        rh = hm.rh_from_dewpoint(temperature, td)
        feels = hm.heat_index_c(temperature, rh)
        return {
            **_MOCK,
            "location": {"latitude": latitude, "longitude": longitude},
            "date": date,
            "analysis": analysis or ["environmental"],
            "environmental": {
                "input_temperature_celsius": temperature,
                "heat_index_celsius": feels,
                "wet_bulb_temperature_celsius": hm.wet_bulb_c(temperature, rh),
                "relative_humidity_percent": rh,
                "heat_risk_band": hm.heat_risk_band(feels),
                "shade_fraction": hm.shade_fraction(latitude, longitude),
            },
        }

    def heatmap(self, polygon_aoi, date_time, granularity=80, analytic_type=ANALYTIC_TCM,
                threshold=30.0, direction="above"):
        _, hours, _ = _hours(date_time)
        coords = _bbox_of(polygon_aoi)
        (min_lon, min_lat, max_lon, max_lat) = coords
        step = max(1, int(granularity)) / 111000.0  # metres -> approx degrees
        cells: list[dict[str, Any]] = []
        lat = min_lat
        while lat <= max_lat:
            lon = min_lon
            while lon <= max_lon:
                lo, hi, rh = _climate(lat, lon)
                series = [hm.air_temperature(lo, hi, h, lat, lon) for h in hours]
                if analytic_type == ANALYTIC_TIME_OF_MEASURE:
                    value = float(max(range(len(hours)), key=lambda i: series[i]))
                    value = hours[int(value)]
                elif analytic_type == ANALYTIC_PERSISTENCE:
                    value = float(sum(1 for t in series if (t >= threshold) == (direction == "above")))
                else:
                    value = round(sum(series) / len(series), 2)
                cells.append({"latitude": round(lat, 5), "longitude": round(lon, 5), "value": value})
                lon += step
            lat += step
        values = [c["value"] for c in cells]
        hottest = max(cells, key=lambda c: c["value"])
        coolest = min(cells, key=lambda c: c["value"])
        return {
            **_MOCK,
            "activity_id": f"heatmap_{uuid.uuid4().hex[:8]}",
            "status": "completed",
            "analytic_type": analytic_type,
            "granularity": granularity,
            "unit": "celsius" if analytic_type == ANALYTIC_TCM else "hours_or_hour_of_day",
            "summary": {
                "cell_count": len(cells),
                "min": min(values), "max": max(values),
                "mean": round(sum(values) / len(values), 2),
                "hottest_cell": hottest, "coolest_cell": coolest,
            },
            "cells": cells,
        }

    def streetview(self, latitude, longitude, vertical_angle=10.0, horizontal_angle=90.0, back_view=False):
        shade = hm.shade_fraction(latitude, longitude)
        svf = round(1.0 - shade * 0.8, 3)
        surface = "vegetation" if shade > 0.6 else "paved" if shade < 0.3 else "mixed"
        return {
            **_MOCK,
            "location": {"latitude": latitude, "longitude": longitude},
            "view": {"vertical_angle": vertical_angle, "horizontal_angle": horizontal_angle, "back_view": back_view},
            "shade_fraction": shade,
            "sky_view_factor": svf,
            "dominant_surface": surface,
        }

    def satellite(self, latitude, longitude, date_time, granularity=80):
        poly = _point_bbox(latitude, longitude, 0.01)
        return self.heatmap(poly, date_time, granularity=granularity)

    def status(self, activity_id):
        return {**_MOCK, "activity_id": activity_id, "status": "completed",
                "note": "mock resolves submissions synchronously"}


def _bbox_of(polygon_aoi: dict[str, Any]) -> tuple[float, float, float, float]:
    try:
        ring = polygon_aoi["features"][0]["geometry"]["coordinates"][0]
    except (KeyError, IndexError, TypeError) as exc:
        raise FortyGuardError(400, "polygon_aoi must be a GeoJSON FeatureCollection with a Polygon.") from exc
    lons = [p[0] for p in ring]
    lats = [p[1] for p in ring]
    return (min(lons), min(lats), max(lons), max(lats))


def _point_bbox(lat: float, lon: float, pad: float) -> dict[str, Any]:
    ring = [
        [lon - pad, lat - pad], [lon + pad, lat - pad],
        [lon + pad, lat + pad], [lon - pad, lat + pad], [lon - pad, lat - pad],
    ]
    return {"type": "FeatureCollection", "features": [
        {"type": "Feature", "properties": {}, "geometry": {"type": "Polygon", "coordinates": [ring]}}]}


# Runtime check that the mock satisfies the adapter contract.
_: FortyGuardClient = MockFortyGuardClient()
